'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DocumentViewer

    Partial Public Class DisplayPage

        '''<summary>
        '''documentViewer1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents documentViewer1 As Global.GleamTech.DocumentUltimate.AspNet.WebForms.DocumentViewerControl

        '''<summary>
        '''documentViewer2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents documentViewer2 As Global.GleamTech.DocumentUltimate.AspNet.WebForms.DocumentViewerControl

        '''<summary>
        '''documentViewer3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents documentViewer3 As Global.GleamTech.DocumentUltimate.AspNet.WebForms.DocumentViewerControl
    End Class
End Namespace
